kafka:
  address: 192.168.99.100:32799
  topic:
    order:
      created: OrderCreatedEvent

zookeeper:
  address: 192.168.99.100:32798

spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      url: http://localhost:8888

info:
  version: @pom.version@
  stage: test

server:
    port: 8091

logging:
  file: /tmp/event-based-shopping-system/logs/@pom.artifactId@/@pom.version@.log
