kafka:
  address: 192.168.99.100:32777
  topic:
    order:
      created: OrderCreatedEvent

zookeeper:
  address: 192.168.99.100:32776

spring:
  application:
    name: commodities-reservation-service
  boot:
    admin:
      url: http://localhost:8888

info:
  version: 1.0.0
  stage: test

server:
    port: 8091

logging:
  file: /tmp/event-based-shopping-system/logs/@pom.artifactId@/@pom.artifactId@.log
