kafka:
  address: 192.168.99.100:32777
  topic:
    order:
      created: OrderCreatedEvent

zookeeper:
  address: 192.168.99.100:32776

spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      url: http://localhost:8888
      client:
        url: http://localhost:8092/webshop

info:
  version: @pom.version@
  stage: test

server:
    port: 8092
    context-path: /webshop

logging:
  file: /tmp/event-based-shopping-system/logs/@pom.artifactId@/@pom.version@.log
